version: '3.7'

services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: crystaldb
      MYSQL_ROOT_PASSWORD: banco
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

volumes:
  db_data:
